### ISSUE TITLE
Cant Compile

### ISSUE THREAD

**Issue by androlool** [sonyxperiadev/vendor-qcom-opensource-wlan-qcacld-3.0#18]
When building the dtb for a Kernel I ran into following issue:

> CC      drivers/staging/wlan-qc/qcacld-3.0/core/hdd/src/wlan_hdd_oemdata.o
In file included from ./include/linux/module.h:18:0,
                 from drivers/staging/wlan-qc/qcacld-3.0/core/hdd/inc/wlan_hdd_includes.h:38,
                 from drivers/staging/wlan-qc/qcacld-3.0/core/hdd/src/wlan_hdd_main.c:36:
./include/linux/moduleparam.h:229:22: warning: initialization from incompatible pointer type
  static const struct kernel_param_ops __param_ops_##name = \
                      ^
drivers/staging/wlan-qc/qcacld-3.0/core/hdd/src/wlan_hdd_main.c:12299:1: note: in expansion of macro 'module_param_call'
 module_param_call(con_mode, con_mode_handler, param_get_int, &con_mode,
 ^
./include/linux/moduleparam.h:229:22: warning: (near initialization for '__param_ops_con_mode.set')
  static const struct kernel_param_ops __param_ops_##name = \
                      ^
drivers/staging/wlan-qc/qcacld-3.0/core/hdd/src/wlan_hdd_main.c:12299:1: note: in expansion of macro 'module_param_call'
 module_param_call(con_mode, con_mode_handler, param_get_int, &con_mode,
 ^
./include/linux/moduleparam.h:229:22: warning: initialization from incompatible pointer type
  static const struct kernel_param_ops __param_ops_##name = \
                      ^
drivers/staging/wlan-qc/qcacld-3.0/core/hdd/src/wlan_hdd_main.c:12302:1: note: in expansion of macro 'module_param_call'
 module_param_call(fwpath, fwpath_changed_handler, param_get_string, &fwpath,
 ^
./include/linux/moduleparam.h:229:22: warning: (near initialization for '__param_ops_fwpath.set')
  static const struct kernel_param_ops __param_ops_##name = \
                      ^
drivers/staging/wlan-qc/qcacld-3.0/core/hdd/src/wlan_hdd_main.c:12302:1: note: in expansion of macro 'module_param_call'
 module_param_call(fwpath, fwpath_changed_handler, param_get_string, &fwpath,
 ^
> 

and 

> CC      drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_pcie.o
> 
> In file included from drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_common.c:45:0:
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h: In function 'pld_snoc_set_wlan_unsafe_channel':
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h:295:2: error: implicit declaration of function 'icnss_set_wlan_unsafe_channel' [-Werror=implicit-function-declaration]
>   return icnss_set_wlan_unsafe_channel(unsafe_ch_list, ch_count);
>   ^
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h: In function 'pld_snoc_get_wlan_unsafe_channel':
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h:301:2: error: implicit declaration of function 'icnss_get_wlan_unsafe_channel' [-Werror=implicit-function-declaration]
>   return icnss_get_wlan_unsafe_channel(unsafe_ch_list, ch_count,
>   ^
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h: In function 'pld_snoc_wlan_set_dfs_nol':
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h:306:2: error: implicit declaration of function 'icnss_wlan_set_dfs_nol' [-Werror=implicit-function-declaration]
>   return icnss_wlan_set_dfs_nol(info, info_len);
>   ^
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h: In function 'pld_snoc_wlan_get_dfs_nol':
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h:310:2: error: implicit declaration of function 'icnss_wlan_get_dfs_nol' [-Werror=implicit-function-declaration]
>   return icnss_wlan_get_dfs_nol(info, info_len);
>   ^
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h: In function 'pld_snoc_get_wlan_mac_address':
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h:341:2: error: implicit declaration of function 'icnss_get_wlan_mac_address' [-Werror=implicit-function-declaration]
>   return icnss_get_wlan_mac_address(dev, num);
>   ^
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h:341:2: warning: return makes pointer from integer without a cast
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h: In function 'pld_snoc_increment_driver_load_cnt':
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h:351:2: error: implicit declaration of function 'icnss_increment_driver_load_cnt' [-Werror=implicit-function-declaration]
>   icnss_increment_driver_load_cnt();
>   ^
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h: In function 'pld_snoc_get_driver_load_cnt':
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h:356:2: error: implicit declaration of function 'icnss_get_driver_load_cnt' [-Werror=implicit-function-declaration]
>   return icnss_get_driver_load_cnt();
>   ^
>   CC      drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.o
>   CC      drivers/staging/wlan-qc/qcacld-3.0/core/utils/pktlog/pktlog_ac.o
> cc1: some warnings being treated as errors
> scripts/Makefile.build:339: recipe for target 'drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_common.o' failed
> make[4]: *** [drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_common.o] Error 1
> make[4]: *** Auf noch nicht beendete Prozesse wird gewartet …
> In file included from drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.c:38:0:
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h: In function 'pld_snoc_set_wlan_unsafe_channel':
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h:295:2: error: implicit declaration of function 'icnss_set_wlan_unsafe_channel' [-Werror=implicit-function-declaration]
>   return icnss_set_wlan_unsafe_channel(unsafe_ch_list, ch_count);
>   ^
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h: In function 'pld_snoc_get_wlan_unsafe_channel':
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h:301:2: error: implicit declaration of function 'icnss_get_wlan_unsafe_channel' [-Werror=implicit-function-declaration]
>   return icnss_get_wlan_unsafe_channel(unsafe_ch_list, ch_count,
>   ^
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h: In function 'pld_snoc_wlan_set_dfs_nol':
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h:306:2: error: implicit declaration of function 'icnss_wlan_set_dfs_nol' [-Werror=implicit-function-declaration]
>   return icnss_wlan_set_dfs_nol(info, info_len);
>   ^
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h: In function 'pld_snoc_wlan_get_dfs_nol':
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h:310:2: error: implicit declaration of function 'icnss_wlan_get_dfs_nol' [-Werror=implicit-function-declaration]
>   return icnss_wlan_get_dfs_nol(info, info_len);
>   ^
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h: In function 'pld_snoc_get_wlan_mac_address':
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h:341:2: error: implicit declaration of function 'icnss_get_wlan_mac_address' [-Werror=implicit-function-declaration]
>   return icnss_get_wlan_mac_address(dev, num);
>   ^
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h:341:2: warning: return makes pointer from integer without a cast
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h: In function 'pld_snoc_increment_driver_load_cnt':
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h:351:2: error: implicit declaration of function 'icnss_increment_driver_load_cnt' [-Werror=implicit-function-declaration]
>   icnss_increment_driver_load_cnt();
>   ^
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h: In function 'pld_snoc_get_driver_load_cnt':
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.h:356:2: error: implicit declaration of function 'icnss_get_driver_load_cnt' [-Werror=implicit-function-declaration]
>   return icnss_get_driver_load_cnt();
>   ^
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.c: In function 'pld_snoc_uevent':
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.c:266:7: error: 'ICNSS_UEVENT_FW_READY' undeclared (first use in this function)
>   case ICNSS_UEVENT_FW_READY:
>        ^
> drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.c:266:7: note: each undeclared identifier is reported only once for each function it appears in
> cc1: some warnings being treated as errors
> scripts/Makefile.build:339: recipe for target 'drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.o' failed
> make[4]: *** [drivers/staging/wlan-qc/qcacld-3.0/core/pld/src/pld_snoc.o] Error 1
> scripts/Makefile.build:653: recipe for target 'drivers/staging/wlan-qc/qcacld-3.0' failed
> make[3]: *** [drivers/staging/wlan-qc/qcacld-3.0] Error 2
> scripts/Makefile.build:653: recipe for target 'drivers/staging/wlan-qc' failed
> make[2]: *** [drivers/staging/wlan-qc] Error 2
> scripts/Makefile.build:653: recipe for target 'drivers/staging' failed
> make[1]: *** [drivers/staging] Error 2
> Makefile:1095: recipe for target 'drivers' failed
> make: *** [drivers] Error 2
>

**Comment by yuanshuaipeng123** [comment]
编译里面去掉-Werror参数就可以了
我的是argument list too long
