### ISSUE TITLE
make[3]: execvp: /bin/sh: Argument list too long

### ISSUE THREAD

**Issue by yuanshuaipeng123** [sonyxperiadev/vendor-qcom-opensource-wlan-qcacld-3.0#24]
when I build qcacld32-ll-nf-debug,the error appread with the follow:

make[3]: execvp: /bin/sh: Argument list too long
make[3]: *** [/home/feng/q/apps_proc/poky/build/tmp-glibc/work/vt_64-oe-linux/qcacld32-ll-nf-debug/git-r8_qsap_perf_perf/wlan/qcacld-3.0/wlan_debug.o] Error 127
make[2]: *** [_module_/home/feng/q/apps_proc/poky/build/tmp-glibc/work/vt_64-oe-linux/qcacld32-ll-nf-debug/git-r8_qsap_perf_perf/wlan/qcacld-3.0] Error 2
make[2]: Leaving directory `/home/feng/q/apps_proc/poky/build/tmp-glibc/work-shared/vt-64/kernel-build-artifacts'
make[1]: *** [sub-make] Error 2
make[1]: Leaving directory `/home/feng/q/apps_proc/poky/build/tmp-glibc/work-shared/vt-64/kernel-source'
ERROR: oe_runmake failed
make: *** [all] Error 2
WARNING: /home/feng/q/apps_proc/poky/build/tmp-glibc/work/vt_64-oe-linux/qcacld32-ll-nf-debug/git-r8_qsap_perf_perf/temp/run.do_compile.1960155:1 exit 1 from 'exit 1'
ERROR: Function failed: do_compile (log file is located at /home/feng/q/apps_proc/poky/build/tmp-glibc/work/vt_64-oe-linux/qcacld32-ll-nf-debug/git-r8_qsap_perf_perf/temp/log.do_compile.1960155)

any ideas?3Q so much.

**Comment by maxshucn** [comment]
The path string is  too much layers:   /home/feng/q/apps_proc/poky/build/tmp-glibc/work/vt_64-oe-linux/qcacld32-ll-nf-debug/git-r8_qsap_perf_perf/wlan/，maybe can work if move it to /wlan/.

**Comment by manszigher** [comment]
I have this issue so dose not seem like QC have solved this but I found this which might explain why this happens

https://www.linuxquestions.org/questions/linux-kernel-70/make%5B3%5D-execvp-bin-sh-argument-list-too-long-compilation-error-4175672251/page2.html

I also found this which is similar but it is not related to qcacld32

https://git.openembedded.org/openembedded-core/commit/?id=1e63a3b7b7915d40bb59976a02b9f53968997ed3

**Comment by manszigher** [comment]
It works when building using Ubuntu 16.04 but not when using 20.04. I have tried comparing the output from "getconf ARG_MAX" but that is the same on both 16.04 and 20.04 the same when it comes to the output from xargs --show-limits

**Comment by abuzarra** [comment]
Hi all,

Any update about this issue?

Thanks,

**Comment by jerpelea** [comment]
This does not look like an OD issue.
Please move the sources to /home/user/android on your drive and try again
